apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    role: database
spec:
  containers:
  - name: master
    image: redis:5.0.3
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
    ports:
    - containerPort: 6379
